# Generated by Django 5.0.4 on 2024-06-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('BF', 'Breakfast'), ('LH', 'Lunch'), ('DN', 'Dinner'), ('DT', 'Desert'), ('DR', 'Drinks'), ('PT', 'Platter'), ('FF', 'Fast Food'), ('PD', 'Popular Dishes'), ('NA', 'New Arrivals')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
