# Generated by Django 5.0.4 on 2024-06-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='marked_price',
        ),
    ]
