# Generated by Django 5.0.4 on 2024-06-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='receiver_number',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='sender_number',
            field=models.IntegerField(default=''),
        ),
    ]
